### ISSUE TITLE
Cassandra Connection Pool Listener gives TTransportException but actual expection raised is AllServersUnavailable

### ISSUE THREAD

**Issue by shbnsndr** [pycassa/pycassa#241]
Hi,

I am using Cassandra 2.2.6 and Python2.7. I have created a Connection Pool with 2 cassandra servers, like below.

`self.pool = ConnectionPool(keyspace='ks', server_list=['192.168.3.1:9160','192.168.3.2:9160'], pool_size=10, prefill=False)`

I have added listener for the connection pool:

`self.pool.add_listener(CassandraPoolMonitor())`

In CassandraPoolMonitor Script I have handled the connection failed event and printed the exception occured, if all my cassandra nodes are down then AllServersUnavailable exception is raised from pycassa, but in the connection failed event I get TTransportException. Below is my Listener Class

`class CassandraPoolMonitor(PoolListener):
    def connection_failed(self, reason):
        print reason['error']`

And also Is there any way that pycassa polls cassandra server to check if the connection is up and running for every 10 seconds.

Thanks

**Comment by thobbs** [comment]
Hi @shbnsndr, I am no longer actively maintaining this project.  I have made you a collaborator for the project, so you are free to commit any fixes that you think are necessary.  Let me know if you have any questions!

**Comment by shbnsndr** [comment]
Thanks thobbs,
